kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc1
  namespace: csi-powerstore
spec:
  storageClassName: powerstore
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 32Gi
